alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  service:
    annotations:
      traefik.ingress.kubernetes.io/affinity: "true"
  ingress:
    enabled: true
    hosts:
      - prometheus.hole
    annotations:
      kubernetes.io/ingress.class: traefik

extraScrapeConfigs: |
  - job_name: co2
    scrape_interval: 60s
    static_configs:
      - targets:
          - 192.168.1.20:8080