{
 "title": "CO2 Sensor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current CO2 Level",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "co2_ppm" }
   ]
  },
  {
   "title": "CO2 Fluctuation Over Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "co2_ppm" }
   ]
  },
  {
   "title": "Current VOC Level",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "tvoc_ppb" }
   ]
  },
  {
   "title": "TVOC Fluctuation Over Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "tvoc_ppb" }
   ]
  },
  {
   "title": "Sensor Errors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "message_invalid_errors", "legendFormat": "Message Invalid" },
    { "expr": "read_reg_invalid_errors", "legendFormat": "Read Register Error" },
    { "expr": "meas_mode_invalid_errors", "legendFormat": "Invalid Measure Mode" },
    { "expr": "max_resistance_errors", "legendFormat": "Max Resistance" },
    { "expr": "max_resistance_errors", "legendFormat": "Heater Fault" },
    { "expr": "heater_supply_errors", "legendFormat": "Heater Supply" },
    { "expr": "unknown_errors", "legendFormat": "Unknown Cause" }
   ]
  }
 ]
}