apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-udp
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
