apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: securewebui
      protocol: TCP
      port: 443
      targetPort: 443

