apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-tcp
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
